project/models.py
from datetime import datetime

from flask_login import UserMixin
from . import db


class User(UserMixin, db.Model):
    # primary keys are required by SQLAlchemy
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

    def __repr__(self) -> str:
        return f'Task: #{self.id}, email: {self.email}'


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey("category.id"))
    status = db.Column(db.String(50), nullable=False)
    expect_hours = db.Column(db.Integer, nullable=True)
    expect_performed = db.Column(db.Integer, nullable=True)
    description = db.Column(db.String(200), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    category = db.relationship(
        "Category", backref="Task", lazy="select", uselist=False
    )

    def __repr__(self) -> str:
        return f'Task: #{self.id}, description: {self.description}'


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(200), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self) -> str:
        return f'Task: #{self.id}, description: {self.description}'

project/__init__.py
import os.path
import sys
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap4
from flask_migrate import Migrate
from flask_login import LoginManager

# init SQLAlchemy so we can use it later in our models
db = SQLAlchemy()
migrate = Migrate()


def create_app():

    STATIC_DIR = os.path.abspath('static')

    app = Flask(__name__, static_folder=STATIC_DIR)

    app.config['SECRET_KEY'] = os.urandom(12).hex()
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    Bootstrap4(app)
    migrate.init_app(app, db)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.signin'
    login_manager.init_app(app)

    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        # since the user_id is just the primary key of our user table, use it in the query for the user
        return User.query.get(int(user_id))

    # blueprint for auth routes in our app
    from .routes.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    # blueprint for  parts of app witch need auth
    from .routes.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

project/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user
from project.models import User
from .. import db

auth = Blueprint('auth', __name__)


@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        remember = True if request.form.get('remember') else False

        user = User.query.filter_by(email=email).first()

        # check if the user actually exists
        # take the user-supplied password, hash it, and compare it to the hashed password in the database
        if not user or not check_password_hash(user.password, password):
            flash('Please check your login details and try again.')
            # if the user doesn't exist or password is wrong, reload the page
            return redirect(url_for('auth.signin'))

        # if the above check passes, then we know the user has the right credentials
        login_user(user, remember=remember)
        return redirect(url_for('main.home_index'))
    else:
        return render_template('auth/signin.html')


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password = request.form.get('password')

        # if this returns a user, then the email already exists in database
        user = User.query.filter_by(email=email).first()

        if user:  # if a user is found, we want to redirect back to signup page so user can try again
            flash('Email address already exists')
            return redirect(url_for('auth.signup'))

        # create a new user with the form data. Hash the password so the plaintext version isn't saved.
        new_user = User(email=email, name=name, password=generate_password_hash(
            password, method='sha256'))

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        return redirect(url_for('main.home_index'))
    else:
        return render_template('auth/signup.html')


@auth.route('/signout')
def signout():
    logout_user()
    return redirect(url_for('main.home_index'))

project/routes/main.py
from flask import Blueprint, render_template, request, redirect
from flask_login import login_required, current_user
from .. import db
from ..models import Task, User, Category

main = Blueprint('main', __name__)


@main.route('/')
@login_required
def home_index():
    return render_template('home/index.html')


# Routes Task

@main.route('/tasks', methods=['GET', 'POST'])
@login_required
def task_index():
    """root route"""
    if request.method == 'POST':
        task = Task(
            description=request.form['description'], category_id=request.form['category_id'], status=request.form[
                'status'], expect_hours=request.form['expect_hours'], expect_performed=request.form['expect_performed'],
            user_id=current_user.id)
        try:
            db.session.add(task)
            db.session.commit()
            return redirect('/tasks')
        except:
            return "Houve um erro, ao inserir a tarefa"
    else:
        tasks = Task.query.filter_by(
            user_id=current_user.id).order_by(Task.date_created).all()
        categories = Category.query.order_by(Category.date_created).all()
        return render_template('task/index.html', tasks=tasks, categories=categories)


@main.route('/tasks/delete/<int:id>')
def task_delete(id):
    """delete a task"""
    task = Task.query.get_or_404(id)
    try:
        db.session.delete(task)
        db.session.commit()
        return redirect('/tasks')
    except:
        return "Houve um erro, ao inserir a tarefa"


@main.route('/tasks/update/<int:id>', methods=['GET', 'POST'])
def task_update(id):
    """update route"""
    task = Task.query.get_or_404(id)
    categories = Category.query.order_by(Category.date_created).all()
    if request.method == 'POST':
        task.description = request.form['description']
        task.category_id = request.form['category_id']
        task.status = request.form['status']
        task.expect_hours = request.form['expect_hours']
        task.expect_performed = request.form['expect_performed']
        try:
            db.session.commit()
            return redirect('/tasks')
        except:
            return "Houve um erro, ao atualizar a tarefa"
    else:
        return render_template('task/update.html', task=task, categories=categories)


# Routes Category


@main.route('/categories', methods=['GET', 'POST'])
# @login_required
def category_index():
    """root route"""
    if request.method == 'POST':
        category = Category(
            description=request.form['description'])
        try:
            db.session.add(category)
            db.session.commit()
            return redirect('categories')
        except:
            return "Houve um erro, ao inserir a tarefa"
    else:
        categories = Category.query.order_by(Category.date_created).all()
        return render_template('category/index.html', categories=categories)


@main.route('/categories/delete/<int:id>')
def category_delete(id):
    """delete a categories"""
    category = Category.query.get_or_404(id)
    try:
        db.session.delete(category)
        db.session.commit()
        return redirect('/categories')
    except:
        return "Houve um erro, ao inserir a tarefa"


@main.route('/categories/update/<int:id>', methods=['GET', 'POST'])
def category_update(id):
    """update route"""
    category = Category.query.get_or_404(id)
    if request.method == 'POST':
        category.description = request.form['description']

        try:
            db.session.commit()
            return redirect('/categories')
        except:
            return "Houve um erro, ao atualizar a tarefa"
    else:
        return render_template('category/update.html', category=category)

project/templates/application.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/main.css') }}">
        {% block styles %}
            <!-- Bootstrap CSS -->
            {{ bootstrap.load_css() }}
        {% endblock %}
        <title>{% block title %}{% endblock %} - Todo</title>
        {% endblock %}
    </head>
    <body>
        <!-- Your page content -->
        {% block content %}{% endblock %}

        {% block scripts %}
            <!-- Optional JavaScript -->
            {{ bootstrap.load_js() }}
        {% endblock %}
    </body>
</html>

project/templates/category/index.html
{% extends "application.html" %}

{% block html_attribs %} lang="pt-BR" {% endblock %}

{% block title %}Categories{% endblock %}

{% block content %}
<div class="container">
   <div class="page-header">
      <h1 class="text-center text-primary">ToDo: Never forget your duties</h1>
   </div>
   {% if categories|length < 1 %} <h4 class="text-center text-warning">There are no categories. Create one below!</h4>
      {% else %}
      <table class="table table-striped">
         <thead>
            <tr>
               <th>Description</th>
               <th>Created</th>
               <th>Actions</th>
            </tr>
         </thead>
         <tbody>
            {% for category in categories %}
            <tr>
               <td class="align-middle">{{ category.description }}</td>
               <td class="align-middle">{{ category.date_created.date() }}</td>
               <td class="align-middle actions">
                  <a class="btn btn-success" href="{{ url_for('main.category_update',id=category.id) }}">Update</a> |
                  <a class="btn btn-danger" href="{{ url_for('main.category_delete',id=category.id) }}">Delete</a>
               </td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
      {% endif %}

      <form class="form" action="{{ url_for('main.category_index') }}" method="POST">
         <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" name="description" id="description" required>
         </div>
          <div class="form-group">    
            <button type="submit" class="btn btn-primary btn-lg btn-block">Add</button>
         </div>
         <div class="form-group">    
            <a class="btn btn-danger btn-lg btn-block" href="{{ url_for('main.home_index')}}">Back</a>
         </div>    
      </form>
</div>
{% endblock %}

project/templates/category/update.html
{% extends "application.html" %}

{% block html_attribs %} lang="pt-BR" {% endblock %}

{% block title %}Categories{% endblock %}

{% block content %}
<div class="container">
   <div class="page-header">
      <h1 class="text-center text-primary">Update Category</h1>
   </div>

   <form class="form" action="{{ url_for('main.category_update', id=category.id) }}" method="POST">
      <div class="form-group">
         <label for="description">Description</label>
         <input type="text" class="form-control" name="description" id="description" value="{{category.description}}" required>
      </div>
      <div class="form-group">    
         <button type="submit" class="btn btn-primary btn-lg btn-block">Update</button>
      </div>   
      <div class="form-group">    
         <a class="btn btn-danger btn-lg btn-block" href="{{ url_for('main.category_index') }}">Cancel</a>
      </div>            
   </form>
</div>
{% endblock %}

project/templates/home/index.html
{% extends "application.html" %}

{% block html_attribs %} lang="pt-BR" {% endblock %}

{% block title %}Index{% endblock %}

{% block content %}

<div class="container">
   
   <div class="page-header py-3">
      <h1 class="text-center text-primary">ToDo: Never forget your duties</h1>
   </div>
   <div class="form-group">    
      <h3 class="text-center py-3">Welcome {{ current_user.name }}!</h3>
   </div>   
   <div class="form-group">    
      <a class="btn btn-primary btn-lg btn-block" href="{{ url_for('main.category_index') }}">Category</a>
   </div>   
   <div class="form-group">    
      <a class="btn btn-primary btn-lg btn-block" href="{{ url_for('main.task_index') }}">Task</a>
   </div>   
   <div class="form-group">    
      <a class="btn btn-danger btn-lg btn-block" href="{{ url_for('auth.signout') }}">Logout</a>
   </div>   

</div>
{% endblock %}

project/templates/task/index.html
{% extends "application.html" %}

{% block html_attribs %} lang="pt-BR" {% endblock %}

{% block title %}Tasks {% endblock %}

{% block content %}
<div class="container">
   <div class="page-header">
      <h1 class="text-center text-primary">ToDo: Never forget your duties</h1>
   </div>
   {% if tasks|length < 1 %} <h4 class="text-center text-warning">There are no tasks. Create one below!</h4>
      {% else %}
      <table class="table table-striped">
         <thead>
            <tr>
               <th>Description</th>
               <th>Category</th>
               <th>Status</th>
               <th>Expected hours</th>
               <th>Expected performed</th>
               <th>Created</th>
               <th>Actions</th>
            </tr>
         </thead>
         <tbody>
            {% for task in tasks %}
            <tr>
               <td class="align-middle">{{ task.description }}</td>
               <td class="align-middle">{{ task.category.description }}</td>
               <td class="align-middle">{{ task.status }}</td>
               <td class="align-middle">{{ task.expect_hours }}</td>
               <td class="align-middle">{{ task.expect_performed }}</td>
               <td class="align-middle">{{ task.date_created.date() }}</td>
               <td class="align-middle actions">
                  <a class="btn btn-success" href="{{ url_for('main.task_update',id=task.id) }}">Update</a> |
                  <a class="btn btn-danger" href="{{ url_for('main.task_delete',id=task.id) }}">Delete</a>
               </td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
      {% endif %}

      <form class="form" action="{{ url_for('main.task_index') }}" method="POST">
         <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" name="description" id="description" required>
         </div>
         <div class="form-group">
            <label for="category_id">Category</label>
            <select name="category_id" id="category_id" class="form-control" required >
               {%  for category in categories  %}
                  <option value="{{ category.id }}">{{ category.description }}</option>
               {% endfor %}
         </select>
         </div>  
         <div class="form-group">
            <label for="status">Status</label>
            <select name="status" id="status" class="form-control" required>
               <option>A Fazer</option>
               <option>Fazendo</option>
               <option>Feita</option>
            </select>
         </div>
         <div class="form-group">
            <label for="expect_hours">Expected hours</label>
            <input type="number" class="form-control" name="expect_hours" id="expect_hours" required>
         </div>
         <div class="form-group">
            <label for="expect_performed">Expected performed</label>
            <input type="number" class="form-control" name="expect_performed" id="expect_performed">
         </div>     
         <div class="form-group">    
            <button type="submit" class="btn btn-primary btn-lg btn-block">Add</button>
         </div>   
         <div class="form-group">    
            <a class="btn btn-danger btn-lg btn-block" href="{{ url_for('main.home_index')}}">Back</a>
         </div>            
      </form>
</div>
{% endblock %}

project/templates/task/update.html
{% extends "application.html" %}

{% block html_attribs %} lang="pt-BR" {% endblock %}

{% block title %}Tasks{% endblock %}

{% block content %}
<div class="container">
   <div class="page-header">
      <h1 class="text-center text-primary">Update Task</h1>
   </div>

   <form class="form" action="{{ url_for('main.task_update', id=task.id) }}" method="POST">
      <div class="form-group">
         <label for="description">Description</label>
         <input type="text" class="form-control" name="description" id="description" value="{{task.description}}" required>
      </div>
      <div class="form-group">
         <label for="category">Category</label>
         <select name="category_id" id="category_id" class="form-control" required>
               {%  for category in categories  %}
                  <option value="{{ category.id }}" {{ "selected" if task.category_id == category.id }} >{{ category.description }}</option>
               {% endfor %}
         </select>
      </div>      
      <div class="form-group">
         <label for="status">Status</label>
         <select name="status" id="status" class="form-control" required>
            <option {{ "selected" if task.status == "A Fazer" }}>A Fazer</option>
            <option {{ "selected" if task.status == "Fazendo" }}>Fazendo</option>
            <option {{ "selected" if task.status == "Feita" }}>Feita</option>
         </select>
      </div>
      <div class="form-group">
         <label for="expect_hours">Expected hours</label>
         <input type="text" class="form-control" name="expect_hours" id="expect_hours" value="{{task.expect_hours}}" required>
      </div>
      <div class="form-group">
         <label for="expect_performed">Expected performed</label>
         <input type="number" class="form-control" name="expect_performed" id="expect_performed" value="{{task.expect_performed}}" >
      </div>     
      <div class="form-group">    
         <button type="submit" class="btn btn-primary btn-lg btn-block">Update</button>
      </div>   
      <div class="form-group">    
         <a class="btn btn-danger btn-lg btn-block" href="{{ url_for('main.task_index') }}">Cancel</a>
      </div>            
   </form>
</div>
{% endblock %}